export { setDecimal } from "./setDecimal";
export { createKey } from "./createKey";
export { tryStorageData } from "./tryStorageData";
export { saveStateInStorage } from "./saveStateInStorage";
export { trimFirstZero } from "./trimFirstZero";
export { addVodkaToState } from "./addVodkaToState";
export { getTotalDrankData } from "./getTotalDrankData";
export { minMaxDayValidation } from "./minMaxDayValidation";
export { minMaxMonthValidation } from "./minMaxMonthValidation";
