export { setDecimal } from "./setDecimal";
export { getCurrentMonth } from "./getCurrentMonth";
export { createKey } from "./createKey";
export { tryStorageData } from "./tryStorageData";
export { saveStateInStorage } from "./saveStateInStorage";
export { trimFirstZero } from "./trimFirstZero";
export { calcMonthData } from "./calcMothData";
export { calcDayData } from "./calcDayData";
export { getTotalDrankData } from "./getTotalDrankData";
